TOPDIR ?= ../..
include $(TOPDIR)/.config

$(FIREMAIL_SUPPORT)_SRC += hardware/firemail/firemail.c \
                           hardware/firemail/fm_io.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk

