TOPDIR ?= ../..
include $(TOPDIR)/.config

$(FIRMWARE_VERSION)_SRC += hardware/firemail/smtp.c
$(FIREMAIL_SUPPORT)_SRC += hardware/firemail/firemail.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk

