TOPDIR ?= ../..
include $(TOPDIR)/.config

$(FIREMAIL_SUPPORT)_SRC += hardware/firemail/firemail.c 

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk

